In [115]:
import numpy as np
import pandas as pd


In [116]:
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
30   73    Male  Average        UG        No
41   23    Male     Good        PG       Yes
35   74    Male     Poor    School       Yes
20   57  Female  Average    School       Yes
1    68  Female     Poor        UG        No

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


# Using Ordinal Encoding first
It is used in input feature having categories in order format

In [118]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

According to dataset we have 4 categorical column. First we have to find the ordinal variable. Which are review, education and purchased. Gender is nominal category. For this thing in review and education we used ordianl encoding and in purchased we used label encoding because label encoding always used in target variable.

###  Using ordinal encoding 

In [119]:
df = df.iloc[:,2:]

In [120]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2, random_state=42)

In [126]:
from sklearn.preprocessing import OrdinalEncoder

In [127]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [128]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [129]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [130]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [131]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [132]:
from sklearn.preprocessing import LabelEncoder

In [133]:
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [134]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [135]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [136]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

## Using One-Hot Encoding

In [137]:
df_car = pd.read_csv('cars.csv')

In [138]:
df_car.sample(5)

brand  km_driven    fuel         owner  selling_price
6132   Maruti      54723  Diesel   First Owner         470000
3323   Maruti     100000  Petrol  Second Owner         100000
251   Hyundai     100000  Petrol  Second Owner         320000
2722      BMW      60000  Diesel  Second Owner         750000
1805  Hyundai       3500  Petrol   First Owner         650000

In [139]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64 
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 317.6+ KB


In [140]:
df_car['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [141]:
df_car['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [142]:
df_car['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

### 1. One-Hot encoding using Pandas

In [143]:
pd.get_dummies(df_car, columns=['fuel', 'owner'], dtype=int)

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

### 2. K-1 OneHotEncoding

In [144]:
pd.get_dummies(df_car, columns=['fuel', 'owner'], drop_first=True, dtype=int)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

## 3. OneHotEncoding Using Sklearn

In [145]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [146]:
X_train, X_test, y_train, y_test = train_test_split(df_car.iloc[:, 0:4], df_car.iloc[:,-1], test_size=0.2, random_state=2)

In [201]:
X_train.shape

(6502, 4)

In [163]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

In [164]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [171]:
# np.hastack() stands for horizontal stack in Numpy. It concatenates arrays side by side (column-wise)
combined = np.hstack([X_train[['brand', 'km_driven']].values, X_train_new])

In [172]:
combined

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

### 4. OneHotEncoding with Top Categories

In [175]:
counts = df_car['brand'].value_counts()

In [178]:
df_car['brand'].nunique()
threshold = 100

In [182]:
repl = counts[counts <= threshold].index


In [192]:
pd.get_dummies(df_car['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
5592    0          1     0      0        0         0       0        0      0   
3961    0          0     0      0        0         0       1        0      0   
4346    0          0     0      0        0         0       1        0      0   
576     0          0     0      0        0         0       1        0      0   
2016    0          0     0      0        0         1       0        0      0   

      Tata  Toyota  Volkswagen  uncommon  
5592     0       0           0         0  
3961     0       0           0         0  
4346     0       0           0         0  
576      0       0           0         0  
2016     0       0           0         0

# Applying Column Transformer

In [194]:
from sklearn.compose import ColumnTransformer

In [206]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OneHotEncoder(sparse_output=False, drop='first',handle_unknown='ignore'), ['brand', 'fuel', 'owner'])
], remainder='passthrough'

)

In [207]:
transformer.fit_transform(X_train).shape

(6502, 38)

In [210]:
transformer.transform(X_test).shape

c:\Users\user\anaconda3\envs\encoding\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


(1626, 38)